package com.mycompany.view;

import com.mycompany.model.Usuario;
import com.mycompany.dao.ClienteDAO;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.awt.Image;
import java.util.List;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JFrame;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class ADmin extends javax.swing.JFrame {

    /**
     * Creates new form ADmin
     */
    public ADmin() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/java/com/mycompany/Assets/logo.jpg");

        // Definindo o ícone da janela
        setIconImage(icon.getImage());
        
        setTitle("Admin Dashboard");
        Clientes();
        Devendo();
        criarGraficoLinha();
        setLocationRelativeTo(null); // Centraliza na tela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Total_clientes = new javax.swing.JLabel();
        Painel_Dividendos = new javax.swing.JPanel();
        jlb2 = new javax.swing.JLabel();
        Dividendos = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jButton1.setText("Ver balanço financeiro");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Balanco(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 199, 133));

        jlb.setBackground(new java.awt.Color(0, 0, 0));
        jlb.setText("Total de clientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Total_clientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Total_clientes.setText("L");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Total_clientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jlb))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Total_clientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Painel_Dividendos.setBackground(new java.awt.Color(255, 153, 153));
        Painel_Dividendos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Painel_Dividendos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Painel_DividendosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Painel_DividendosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Painel_DividendosMouseExited(evt);
            }
        });

        jlb2.setBackground(new java.awt.Color(0, 0, 0));
        jlb2.setText("Dividendos");

        Dividendos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Dividendos.setText("L");

        javax.swing.GroupLayout Painel_DividendosLayout = new javax.swing.GroupLayout(Painel_Dividendos);
        Painel_Dividendos.setLayout(Painel_DividendosLayout);
        Painel_DividendosLayout.setHorizontalGroup(
            Painel_DividendosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DividendosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlb2)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(Painel_DividendosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Painel_DividendosLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(Dividendos)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );
        Painel_DividendosLayout.setVerticalGroup(
            Painel_DividendosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DividendosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Painel_DividendosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Painel_DividendosLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(Dividendos)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Painel_Dividendos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_Dividendos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarGraficoLinha() {
        // Dados
        double[] meses = {1, 2, 3, 4, 5, 6};
        double[] lucro = {1500, 2300, 1800, 2700, 3000, 3500};

        // Cria gráfico
        XYChart chart = new XYChartBuilder()
                .width(600)
                .height(300)
                .title("Lucro Mensal - Clínica Veterinária")
                .xAxisTitle("Mês")
                .yAxisTitle("Lucro (R$)")
                .build();

        chart.addSeries("Lucro", meses, lucro);

        // Coloca o gráfico no painel
        XChartPanel<XYChart> painelGrafico = new XChartPanel<>(chart);
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(painelGrafico, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
    }

    
    private void Balanco(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Balanco
        abrirGraficoBarras();
    }//GEN-LAST:event_Balanco

    private void Painel_DividendosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Painel_DividendosMouseClicked
        new Dividendos().setVisible(true);
    }//GEN-LAST:event_Painel_DividendosMouseClicked

    private void Painel_DividendosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Painel_DividendosMouseEntered
        Painel_Dividendos.setBackground(Color.RED);
    }//GEN-LAST:event_Painel_DividendosMouseEntered

    private void Painel_DividendosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Painel_DividendosMouseExited
        Painel_Dividendos.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_Painel_DividendosMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pagar();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADmin().setVisible(true);
            }
        });  
    }

    private void abrirGraficoBarras() {
        new DespesasXReceitas().setVisible(true);
    }
    
    private void Pagar() {
        new Pagar().setVisible(true);
    }
    
    /*
    private void Clientes_Total(){
    Random r = new Random();
    int numR = r.nextInt(1,100);
    Total_clientes.setText(String.valueOf(numR));
    }
    */
    private void Devendo() {
    ClienteDAO dao = new ClienteDAO(); // ou UsuarioDAO se preferir
    List<Usuario> devedores = dao.getClientesDevedores(); // retorna só os com status = 'n'

    // Atualiza o JLabel ou JTextField chamado Dividendos
    Dividendos.setText(Integer.toString(devedores.size()));

    // Para debug opcional
    /*
    for (Usuario u : devedores) {
        System.out.println(u);
    }
    */
}

    private void Clientes(){
        ClienteDAO dao = new ClienteDAO();
        List<Usuario> Clientes = dao.getClientes();

        Total_clientes.setText(Integer.toString(Clientes.size()));
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dividendos;
    private javax.swing.JPanel Painel_Dividendos;
    private javax.swing.JLabel Total_clientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlb;
    private javax.swing.JLabel jlb2;
    // End of variables declaration//GEN-END:variables
}
