package com.mycompany.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.List;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.XChartPanel;
/**
 *
 * @author user
 */
public class DespesasXReceitas extends javax.swing.JFrame {

    /**
     * Creates new form DespesasXReceitas
     */
    public DespesasXReceitas() {
        initComponents();
        ImageIcon icon = new ImageIcon("src/main/java/com/mycompany/Assets/logo.jpg");
        // Definindo o ícone da janela
        setIconImage(icon.getImage());
        setTitle("Balanço Financeiro Mensal");
        Barra();
        setLocationRelativeTo(null); // Centraliza na tela
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Opcoes1 = new javax.swing.JComboBox<>();
        Selecionar_Mes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        Opcoes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun" }));

        Selecionar_Mes.setText("Selecionar");
        Selecionar_Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selecionar_MesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Selecionar_Mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Opcoes1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Opcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Selecionar_Mes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Selecionar_MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selecionar_MesActionPerformed
        Barra();
    }//GEN-LAST:event_Selecionar_MesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DespesasXReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DespesasXReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DespesasXReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DespesasXReceitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DespesasXReceitas().setVisible(true);
            }
        });
    }

    private void Barra() {
    List<String> meses = Arrays.asList("Jan", "Fev", "Mar", "Abr", "Mai", "Jun");
    List<Double> receitas = Arrays.asList(5000.0, 6200.0, 5800.0, 7100.0, 6900.0, 7500.0);
    List<Double> despesas = Arrays.asList(3200.0, 4000.0, 3500.0, 3800.0, 4100.0, 4300.0);

    String mesSelecionado = (String) Opcoes1.getSelectedItem();

    List<String> mesesFiltrados;
    List<Double> receitasFiltradas;
    List<Double> despesasFiltradas;

    if (mesSelecionado.equals("Todos")) {
        mesesFiltrados = meses;
        receitasFiltradas = receitas;
        despesasFiltradas = despesas;
    } else {
        int index = meses.indexOf(mesSelecionado);
        if (index == -1) return; // segurança

        mesesFiltrados = Arrays.asList(meses.get(index));
        receitasFiltradas = Arrays.asList(receitas.get(index));
        despesasFiltradas = Arrays.asList(despesas.get(index));
    }

    CategoryChart chart = new CategoryChartBuilder()
            .width(jPanel1.getWidth())
            .height(jPanel1.getHeight())
            .title("Balanço Financeiro Mensal")
            .xAxisTitle("Mês")
            .yAxisTitle("Valor (R$)")
            .build();

    chart.addSeries("Receitas", mesesFiltrados, receitasFiltradas);
    chart.addSeries("Despesas", mesesFiltrados, despesasFiltradas);

    jPanel1.removeAll(); // limpar painel antigo
    XChartPanel<CategoryChart> painelGrafico = new XChartPanel<>(chart);
    jPanel1.setLayout(new java.awt.BorderLayout());
    jPanel1.add(painelGrafico, java.awt.BorderLayout.CENTER);
    jPanel1.revalidate();
    jPanel1.repaint();

}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Opcoes1;
    private javax.swing.JButton Selecionar_Mes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
